config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  resources :orders do
    member do
      get 'cancel', as: 'cancel'
      post 'cancel', as: 'canceled'
    end
  end

  resources :line_items

  resource :cart, :only => [:show, :update, :destroy]

  devise_for :users, :controllers=> { registrations: 'registrations' }

  resources :products

  resources :users

  get '/review' => 'products#review'

  get ':category_id', to: 'products#index', as: 'category_products'
  root 'products#index'

  get 'accountinformations/show'

  #Definition der Variable store, um bei Controllern auf diese verweisen zu können, z.B. Einkaufswagen gelöscht wird
  root to: 'products#index', as: 'store'

  
  get '/checkout/addresses' => 'checkout#addresses'
  get '/checkout/overview' => 'checkout#overview'

  post '/checkout/addresses' => 'checkout#addresses'
  post '/checkout/overview' => 'checkout#overview'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :set_cart, only: [:addresses, :overview]
    
  def addresses
    if @cart.invoice_firstname.nil?
      if current_user.company.present?
        @cart.invoice_company = current_user.company
      end
        @cart.invoice_firstname = current_user.firstname
        @cart.invoice_lastname = current_user.lastname
      if current_user.zipcode and current_user.site and current_user.street and current_user.country
        @cart.invoice_zipcode = current_user.zipcode
        @cart.invoice_site = current_user.site
        @cart.invoice_street = current_user.street
        @cart.invoice_country = current_user.country
      end
    end

    if params[:cart].present?
      if !@cart.update(cart_params)
        flash.alert = "Rechnungs- und/oder Lieferadresse konnte nicht geupdatet werden."
      end
    end
  end

  def overview
    if params[:cart].present?
      if @cart.update(cart_params)
        render :overview
      else
        flash.alert = "Rechnungs und/oder Lieferadresse konnte nicht geupdatet werden."
        render :addresses
      end
    else
      render :overview
    end
  end

  private

  def set_cart
    @cart = current_cart
  end

  def cart_params
    #hier nur invoice address und shipping adress felder permitten von der addresses view
    params[:cart].permit(:invoice_company, :invoice_firstname, :invoice_lastname, :invoice_zipcode, :invoice_site, :invoice_street, :invoice_country, :shipping_firstname, :shipping_lastname, :shipping_zipcode, :shipping_site, :shipping_street, :shipping_country, :shipping_company, :optional_invoice_address, :shipping_method_id, :payment_id, line_items_attributes: [:id, :quantity, :_destroy])
  end

end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/addresses.html.erb
<div class="row">
  <div class=".col-xs-3">
    <%= form_for(@cart, :url => checkout_overview_path, :method => :post) do |f| %>
      <h1>Adresseingabe</h1>
      <%= render partial: 'checkout/shared/checkout_head' %>
        </div>
      <div class="left_box"> 
        <h3>Rechnungsadresse</h3>
      </div>
      <div class="blank_div">
      </div>
        <div class="right_box">
          <h3>Lieferadresse</h3>
        </div>
      <div class="full_box">
        <div class="field">
          <%= f.check_box :optional_invoice_address %> Lieferadresse und Rechnungsadresse sind identisch <br />
        </div>
      </div> 
      <div class="left_box">   
        <table class="table">
          <tr>
            <th><%= f.label :company %></th>
            <td><%= f.text_field :invoice_company %></td>
          </tr>
          <tr>
            <th><%= f.label :firstname %></th>
            <td><%= f.text_field :invoice_firstname %></td>
          </tr>
          <tr>
            <th><%= f.label :lastname %></th>
            <td><%= f.text_field :invoice_lastname %></td>
          </tr>         
          <tr>
            <th><%= f.label :street %></th>
            <td><%= f.text_field :invoice_street %></td>
          </tr>
          <tr>
            <th><%= f.label :zipcode %></th>
            <td><%= f.text_field :invoice_zipcode %></td>
          </tr>
          <tr>
            <th><%= f.label :site %></th>
            <td><%= f.text_field :invoice_site %></td>
          </tr>
          <tr>
            <th><%= f.label :country %></th>
            <td><%= f.text_field :invoice_country %></td>
          </tr>
      </table>      
    </div>
    <div class="right_box">
      <table class="table">
        <tr>
          <th><%= f.label :company %></th>
          <td><%= f.text_field :shipping_company %></td>
        </tr>
        <tr>
          <th><%= f.label :firstname %></th>
          <td><%= f.text_field :shipping_firstname %></td>
        </tr>
        <tr>
          <th><%= f.label :lastname %></th>
          <td><%= f.text_field :shipping_lastname %></td>
        </tr>         
        <tr>
          <th><%= f.label :street %></th>
          <td><%= f.text_field :shipping_street %></td>
        </tr>
        <tr>
          <th><%= f.label :zipcode %></th>
          <td><%= f.text_field :shipping_zipcode %></td>
        </tr>
        <tr>
          <th><%= f.label :site %></th>
          <td><%= f.text_field :shipping_site %></td>
        </tr>
        <tr>
          <th><%= f.label :country %></th>
          <td><%= f.text_field :shipping_country %></td>
        </tr>
      </table>      
    </div> 
    <div class="full_box">    
      <%= f.submit 'Weiter', class: 'btn btn-default btn-xs' %>
    </div>
  <% end %>
  </div>
</div>

app/views/checkout/overview.html.erb
<div class="row">
  <div class=".col-xs-3">
    <%= form_for(@cart, :url => orders_path, :method => :post) do |f| %>
    <h1>Bestellübersicht</h1>
    <%= render partial: 'checkout/shared/checkout_head' %>
      <% if @cart.optional_invoice_address %>

        <%= render partial: 'checkout/shared/address' %>
      <% else %>

        <%= render partial: 'checkout/shared/address' %>

        <div class="blank_div">
        </div>
        <% if @cart.shipping_zipcode and @cart.shipping_site %>
          <div class="right_box">
            <h3>Lieferadresse</h3> 
            <% if @cart.shipping_company.present? %>
                <p><%= @cart.shipping_company %></p>
            <% end %>
            <p><%= "#{@cart.shipping_firstname} #{@cart.shipping_lastname}" %></p>
            <p><%= @cart.shipping_street %></p>
            <p><%= "#{@cart.shipping_zipcode} #{@cart.shipping_site}" %></p>
            <p><%= @cart.shipping_country %></p>
          </div>
      <% end %>
      <% end %> 
    <div class="full_box">   
      <% if (@cart.shipping_firstname.present? and @cart.shipping_lastname.present? and @cart.shipping_street? and @cart.shipping_zipcode and @cart.shipping_country) or ( @cart.invoice_site and @cart.invoice_zipcode and @cart.invoice_country and @cart.invoice_street) or (current_user.zipcode and current_user.street and current_user.country and current_user.site) %>    
        <%= f.submit 'Kostenpflichtig bestellen', class: 'btn btn-default btn-xs' %>
      <% else %>
      <p><strong> Sie müssen erst eine vollständige Adresse angeben um die Bestellung abschließen zu können!</strong></p>
      <% end %>
    </div>
  <% end %>
  </div>
</div>