config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  resources :orders do
    member do
      get 'cancel', as: 'cancel'
      post 'cancel', as: 'canceled'
    end
  end

  resources :line_items

  resource :cart, :only => [:show, :update, :destroy]

  devise_for :users, :controllers=> { registrations: 'registrations' }

  resources :products

  resources :users

  get '/review' => 'products#review'

  get ':category_id', to: 'products#index', as: 'category_products'
  root 'products#index'

  get 'accountinformations/show'

  #Definition der Variable store, um bei Controllern auf diese verweisen zu können, z.B. Einkaufswagen gelöscht wird
  root to: 'products#index', as: 'store'

  
  get '/checkout/addresses' => 'checkout#addresses'
  get '/checkout/overview' => 'checkout#overview'

  post '/checkout/addresses' => 'checkout#addresses'
  post '/checkout/overview' => 'checkout#overview'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_one :user
  has_one :cart
  belongs_to :payment
  has_many :order_line_items

  enum status: [:process, :payment, :shipping, :canceled]

  def add_line_items_from_cart(cart)
    cart.line_items.each do |line_item|
      order_line_item = OrderLineItem.new
      order_line_item.product_name = line_item.product.name
      order_line_item.product_short_description = line_item.product.short_description
      order_line_item.product_description = line_item.product.description
      order_line_item.product_price = line_item.product.price
      order_line_item.product_vat_rate = line_item.product.vat_rate
      order_line_item.product_quantity = line_item.quantity
      order_line_items << order_line_item
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :cancel, :destroy]

  def index
    if current_user.admin
      @orders = Order.all
    else
      @orders = current_user.orders
    end
  end

  def show
  end

  def edit
  end
 
  def create
    @order = Order.new
    @order.add_line_items_from_cart(current_cart)

    @order.total_price = current_cart.total_price
    @order.total_vat = current_cart.total_vat
    @order.user_id = current_user.id
    @order.order_date = Time.now
    @order.payment_id = current_cart.payment_id
    @order.shipping_method_id = current_cart.shipping_method_id
    @order.shipping_method_name = current_cart.shipping_method.name
    @order.shipping_method_price = current_cart.shipping_method.price

    if current_cart.shipping_firstname.present?
      @order.shipping_company = current_cart.shipping_company
      @order.shipping_firstname = current_cart.shipping_firstname
      @order.shipping_lastname = current_cart.shipping_lastname
      @order.shipping_street = current_cart.shipping_street
      @order.shipping_zipcode = current_cart.shipping_zipcode
      @order.shipping_site = current_cart.shipping_site
      @order.shipping_country = current_cart.shipping_country
    end
      @order.invoice_company = current_cart.invoice_company
      @order.invoice_firstname = current_cart.invoice_firstname
      @order.invoice_lastname = current_cart.invoice_lastname
      @order.invoice_street = current_cart.invoice_street
      @order.invoice_zipcode = current_cart.invoice_zipcode
      @order.invoice_site = current_cart.invoice_site
      @order.invoice_country = current_cart.invoice_country

    @order.optional_invoice_address = current_cart.optional_invoice_address

    if Order.last.nil?
      @order.order_number = 100000
    else
      @order.order_number = Order.last.order_number + 1
    end
  
    if @order.save
      current_cart.destroy
      render :created
    else
      redirect_to checkout_overview_path, :alert => 'Fehler Nr. 42'
    end
  end

  def cancel
    @order.status = :canceled

    if @order.save
      redirect_to orders_url, notice: 'Bestellung wurde erfolgreich storniert.'
    else
      redirect_to orders_url, alert: 'Bestellung wurde nicht storniert.'
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      #format.html { redirect_to orders_url, notice: 'Bestellung wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to edit_order_path(@order), notice: 'Bestellung wurde erfolgreich geändert.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_number, :status, :user_id, :shipping_method_id, :payment_id, :total_price, :order_date)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_number %><br>
    <%= f.number_field :order_number %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.datetime_select :order_date %>
  </div>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(Order.statuses.map { |k,v| [I18n.t('activerecord.attributes.order.status_values.' + k), k] }, @order.status) %>
  </div>
  <div class="actions">
    <%= f.submit 'Order aktualisieren' ,class: 'btn btn-default btn-xs'%>
  </div>
<% end %>

app/views/orders/created.html.erb
<div class="row">
  <div class=".col-xs-3">
  	<h1><strong>Vielen Dank für Ihre Bestellung!</strong></h1>
  	<br />
  	<br />
	  	<h4>Bestell-Nr. <strong><%= @order.order_number %></strong></h4>
	  	<br />
			<%= render partial: 'orders/shared/products' %>
			<%= render partial: 'orders/shared/delivery_and_payment' %>
	    <% if @order.optional_invoice_address %>
				<%= render partial: 'orders/shared/address' %>
			<% else %>
				<%= render partial: 'orders/shared/address' %>
			<div class="blank_div">
      </div>
	      <% if @order.shipping_zipcode and @order.shipping_site %>
	        <%= render partial: 'orders/shared/shipping' %>
	      <% end %>
			<% end %> 
			<%= render partial: 'orders/shared/account_data' %>
			  <div class="full_box">
				 <p> Ihre Bestellung können sie jederzeit unter <strong><%= link_to 'Bestellungen', orders_path %></strong> anschauen </p>

			  <td><%= link_to 'Bestellung stornieren', cancel_order_path(@order), class: 'btn btn-default btn-md'%></td>
			</div>
		</div>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @order, class: 'btn btn-default btn-xs' %> |
<%= link_to 'Zurück', orders_path, class: 'btn btn-default btn-xs' %>

app/views/orders/failure.html.erb
FAILURE!

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bestellübersicht</h1>

<table class="table">
  <thead>
    <tr>
      <th>Bestellnummer</th>
      <% if current_user.admin %>
       <th>Benutzer</th>
      <% end %>
      <th>Gesamtpreis</th>
      <th>Bestelldatum</th>
      <th>Bestellstatus </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_number %></td>
        <% if current_user.admin %>
          <td><%= order.user_id %></td>
        <% end %>
        <td><%= number_to_currency(order.total_price + order.shipping_method_price) %></td>
        <td><%= I18n.l order.order_date %></td>
        <td><%= I18n.t('activerecord.attributes.order.status_values.'+ order.status) %></td>
        <td><%= link_to order do%>
        <i class="fa fa-eye">Anzeigen</i>
        <% end %>
        </td>
        <% if current_user.admin %>
        <td><%= link_to 'Bearbeiten', edit_order_path(order) %></td>
        <td><%= link_to 'Löschen', order, method: :delete, data: { confirm: 'Sind Sie sich sicher?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<div class="row">
  <div class=".col-xs-3">
  	<br />
	    <h2>Bestell-Nr. <strong><%= @order.order_number %></strong></h2>
	    <br />
				<%= render partial: 'orders/shared/products' %>
				<%= render partial: 'orders/shared/delivery_and_payment' %>
		    <% if @order.optional_invoice_address %>
					<%= render partial: 'orders/shared/address' %>
				<% else %>
					<%= render partial: 'orders/shared/address' %>
					<div class="blank_div">
		      </div>
		      <% if @order.shipping_zipcode and @order.shipping_site %> 
		        <%= render partial: 'orders/shared/shipping' %>
		      <% end %>
				<% end %> 
				<%= render partial: 'orders/shared/account_data' %>
			  <div class="full_box">
				  <p> Ihre Bestellung können sie jederzeit unter <strong><%= link_to 'Bestellungen', orders_path %></strong> anschauen </p>
				<% if @order.status != "canceled" %>
			  	<td><%= button_to 'Bestellung stornieren', {:controller => "orders", :action => "cancel"}, class: 'btn btn-default btn-md'%></td>
			  <% end %>
			</div>
		</div>
  </div>
</div>

app/views/orders/success.html.erb
SUCCESS!