config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  resources :orders do
    member do
      get 'cancel', as: 'cancel'
      post 'cancel', as: 'canceled'
    end
  end

  resources :line_items

  resource :cart, :only => [:show, :update, :destroy]

  devise_for :users, :controllers=> { registrations: 'registrations' }

  resources :products

  resources :users

  get '/review' => 'products#review'

  get ':category_id', to: 'products#index', as: 'category_products'
  root 'products#index'

  get 'accountinformations/show'

  #Definition der Variable store, um bei Controllern auf diese verweisen zu können, z.B. Einkaufswagen gelöscht wird
  root to: 'products#index', as: 'store'

  
  get '/checkout/addresses' => 'checkout#addresses'
  get '/checkout/overview' => 'checkout#overview'

  post '/checkout/addresses' => 'checkout#addresses'
  post '/checkout/overview' => 'checkout#overview'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/product.rb
require 'open-uri'

class Product < ActiveRecord::Base
  attr_reader :avatar_remote_url

  has_many :reviews
  has_many :line_items
  has_many :categories, through: :product_categories
  has_many :product_categories

  validates :name, :description, :short_description, :price, :vat_rate, :avatar, :categories, presence: true
  validates :short_description, length: {minimum: 50, maximum: 100}, allow_blank: true

  has_attached_file :avatar, :styles => { :large =>'400x400', :medium => '350x250', :small => '200x200', :mini => '100x100' }, :default_url => '/images/:style/missing.png'
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def avatar_remote_url(url_value)
    self.avatar = URI.parse(url_value)
  end

  def vat
    self.price * self.vat_rate / 100
  end

  private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items still present')
      return false
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! , only: [:edit, :update, :destroy, :new, :create]
  before_filter :is_admin? , only: [:edit, :update, :destroy, :new, :create]

  def index
    @products = if params[:category_id]
                  Category.find(params[:category_id]).products
                else
                  Product.all
                end
    @products = @products.paginate(:page => params[:page], :per_page => 21)
  end

  def show
  end

  def review
    @product = Product.find(params[:id])
    @review = Review.new
    @reviews = @product.reviews
  end

  def is_admin?
    if current_user.admin?
      true
    else
      redirect_to :products, alert: 'Sorry, du musst Admin sein um das zu tun!'
    end
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Produkt wurde erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Produkt wurde erfolgreich aktualisiert.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Produkt wurde erfolgreich entfernt.' }
      format.json { head :no_content }
    end
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :short_description, :in_stock, :price, :vat_rate, :avatar, category_ids: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true, :role => 'form' }  ) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :vat_rate %><br>
    <%= f.text_field :vat_rate, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :categories %><br>
    <%= f.collection_select :category_ids, Category.all, :id, :name, { selected: @product.categories.map(&:id), include_blank: false }, multiple: true, class: 'form-control', role: 'dropdown' %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'btn btn-default' %>
  </div>

  <div class="actions">
    <%= f.button '', :class => 'btn btn-default', data: { disable_with: "Speichern..." } do %>
      <i class="fa fa-save"></i> Speichern
    <% end %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Produkt bearbeiten</h1>

<%= render 'form' %>

<%= link_to products_path, class: 'btn btn-default btn-xs' do %>
	<i class="fa fa-caret-left"></i> Zurück
<% end %>

app/views/products/index.html.erb
<h1>Produkte</h1>

  <div class="row">
    <% @products.each do |product| %>

    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to image_tag(product.avatar.url(:medium)), product %>
        <div class="caption">
          <h3><%= link_to product.name, product %></h3>
          <p><%= simple_format product.short_description %></p>
          <% if product.in_stock %>
            <p class="text-success">Lieferbar</p>
          <% else %>
            <p class="text-warning">Nicht lieferbar</p>
          <% end %>
          <strong><%= number_to_currency(product.price) %></strong>
        </div>
      </div>
    </div>
    <% end %>
  </div>

<br>

<% if user_signed_in? and current_user.admin %>
  <br />
    <%= link_to new_product_path, class: 'btn btn-default btn-xs' do %>
      <i class="fa fa-plus"></i> Produkt anlegen
    <% end %>
<% end %>

<%= will_paginate @products, renderer: BootstrapPagination::Rails %>

app/views/products/new.html.erb
<h1>Neues Produkt hinzufügen</h1>

<%= render 'form' %>

<%= link_to 'Zurück', products_path, class: 'btn btn-default' %>

app/views/products/review.html.erb
<%= render partial: 'products/shared/producthead' %>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <ul class="nav nav-tabs" role="tablist">
        <li class><%= link_to 'Beschreibung', @product %></li>
        <li class="active"><%= link_to 'Kundenbewertung', :controller => :products, :action => :review, :id => @product %></li>
      </ul>

      <div>
        <br>
        <% if user_signed_in? %>
            <%= form_for(@review) do |f| %>
                <% if @review.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

                      <ul>
                        <% @review.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>


                <div class="form-group">
                  <%= f.label :description %><br>
                  <%= f.text_area :description,class: 'form-control' %>
                  <%= f.label :grade %><br>
                  <%= f.number_field :grade, :min => 1, :max => 6, class: 'form-control' %>
                  <%= f.hidden_field :username, :value => current_user.firstname %>
                  <%= f.hidden_field :product_id, :value => @product.id %>
                </div>

                <div class="actions">
                  <%= f.button '', :class => 'btn btn-default', data: { disable_with: "Speichern..." } do %>
                      <i class="fa fa-save"></i> Speichern
                  <% end %>
                </div>
                <hr>
            <% end %>
        <% else %>
          <p> Du musst angemeldet sein um eine Bewertung zu schreiben </p>
        <% end %>
      </div>
      <div>
        <% @reviews.each do |review| %>
            <div class = "well">
              <h4><%= review.username %></h4>
              <p>Note: <%= review.grade %></p>
              <p><%= review.description %></p>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<%= render partial: 'products/shared/producthead' %>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active"><%= link_to 'Beschreibung', @product %></li>
        <li><%= link_to 'Kundenbewertung', :controller => :products, :action => :review, :id => @product %></li>
      </ul>

      <p> <%= simple_format @product.description %></p>

    </div>
  </div>
</div>