config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  resources :orders do
    member do
      get 'cancel', as: 'cancel'
      post 'cancel', as: 'canceled'
    end
  end

  resources :line_items

  resource :cart, :only => [:show, :update, :destroy]

  devise_for :users, :controllers=> { registrations: 'registrations' }

  resources :products

  resources :users

  get '/review' => 'products#review'

  get ':category_id', to: 'products#index', as: 'category_products'
  root 'products#index'

  get 'accountinformations/show'

  #Definition der Variable store, um bei Controllern auf diese verweisen zu können, z.B. Einkaufswagen gelöscht wird
  root to: 'products#index', as: 'store'

  
  get '/checkout/addresses' => 'checkout#addresses'
  get '/checkout/overview' => 'checkout#overview'

  post '/checkout/addresses' => 'checkout#addresses'
  post '/checkout/overview' => 'checkout#overview'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:trackable, :timeoutable, :lockable, :rememberable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  belongs_to :shipping_method
  belongs_to :payment

  accepts_nested_attributes_for :line_items

  #validates :invoice_firstname, :invoice_lastname, :invoice_zipcode, :invoice_site, :invoice_street, :invoice_country, presence: true

  def add_product(product_id)
    new_product = line_items.find_by_product_id(product_id)
    if new_product
      if new_product.quantity.nil?
        new_product.quantity = 1
      else
        new_product.quantity += 1
      end
    else
      new_product = line_items.build(:product_id => product_id)
    end

    new_product
  end

  def total_price
    line_items.to_a.sum{ |item| item.total_price }
  end

  def total_vat
    line_items.to_a.sum{ |item| item.total_vat }
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, through: :product_categories
  has_many :product_categories

  def to_param
  	"#{id}-#{name.parameterize}"
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end

  def total_vat
    product.vat * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_one :user
  has_one :cart
  belongs_to :payment
  has_many :order_line_items

  enum status: [:process, :payment, :shipping, :canceled]

  def add_line_items_from_cart(cart)
    cart.line_items.each do |line_item|
      order_line_item = OrderLineItem.new
      order_line_item.product_name = line_item.product.name
      order_line_item.product_short_description = line_item.product.short_description
      order_line_item.product_description = line_item.product.description
      order_line_item.product_price = line_item.product.price
      order_line_item.product_vat_rate = line_item.product.vat_rate
      order_line_item.product_quantity = line_item.quantity
      order_line_items << order_line_item
    end
  end

end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
  belongs_to :oder
end

app/models/order_transaction.rb
class OrderTransaction < ActiveRecord::Base
  belongs_to :order
  serialize :params
  
  def response=(response)
    self.success       = response.success?
    self.authorization = response.authorization
    self.message       = response.message
    self.params        = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success       = false
    self.authorization = nil
    self.message       = e.message
    self.params        = {}
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  has_many :cart
  has_many :order
end

app/models/product.rb
require 'open-uri'

class Product < ActiveRecord::Base
  attr_reader :avatar_remote_url

  has_many :reviews
  has_many :line_items
  has_many :categories, through: :product_categories
  has_many :product_categories

  validates :name, :description, :short_description, :price, :vat_rate, :avatar, :categories, presence: true
  validates :short_description, length: {minimum: 50, maximum: 100}, allow_blank: true

  has_attached_file :avatar, :styles => { :large =>'400x400', :medium => '350x250', :small => '200x200', :mini => '100x100' }, :default_url => '/images/:style/missing.png'
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def avatar_remote_url(url_value)
    self.avatar = URI.parse(url_value)
  end

  def vat
    self.price * self.vat_rate / 100
  end

  private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items still present')
      return false
    end
  end

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  validates_inclusion_of :grade, :in => 1..6
end

app/models/shipping_method.rb
class ShippingMethod < ActiveRecord::Base
  has_many :carts

  def total_vat
  	self.vat_rate * self.price / 100
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, :lastname, presence: true
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "dotDotTrue" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all", media: "all", "data-turbolinks-track" => true %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", media: "all", "data-turbolinks-track" => true %>
  </head>
  <body>
      <div id="wrapper">
        <div id="inhalt">
            <%= render partial: 'shared/navigation' %>

                <div class="container">
                  <div class="row">
                    <div class="col-lg-12">
                      <%= bootstrap_flash %>
                      <%= yield %>
                    </div>
                         <!--   <div class="col-lg-3">
                              <div class="well sidebar-nav">
                                <h4>Links</h4>
                                <hr>
                                <ul class="nav nav-list">
                                  <li><%= link_to "Warenkorb", cart_path  %></li>


                                </ul>
                              </div>
                            </div> -->
                  </div><!--/row-->


                </div> <!-- /container -->
          </div>

        <div id="footer">
          <footer>
            <div class="container">
              <div class="row">
                <div class="col-lg-3">
                    <p>&copy; 2015 dotDotTrue
                    <br> Musterstr. 8
                    <br> 48151 Münster
                    </p>
                  </div>
                <div class="col-lg-3">
                  <p>
                    Telefon: 01234 / 56789
                    <br>Telefax: 01234 / 9 56789
                    <br>E-Mail: info@dotdottrue.com
                  </p>
                </div>
                <div class="col-lg-3">
                  <p>
                    Niclas Christ, Dennis Russ,
                    <br> Tobias Kappert, Eduard Schartner
                  </p>
                </div>
                <div class="col-lg-3">
                  Konto:
                  <br>Sparkasse Münschterland Nord
                  <br>IBAN DE87340014513452345
                </div>
                </div>
            </div>
          </footer>
        </div>

      </div>
  </body>
</html>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a> <%= link_to 'dotDotTrue', root_path, class: 'navbar-brand' %> </a>
    <div class="nav navbar-nav">
      <ul class="nav navbar-nav">
        <% Category.all.each do |category|  %>
          <li><%= link_to category.name, category_products_path(category)  %></li>
        <% end %>
       </ul>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to cart_path do %> <i class="fa fa-shopping-cart fa-2x"></i> <% end %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <% if user_signed_in? %> Willkommen, <%= current_user.firstname %>!<% else %> Sie sind nicht eingeloggt. <%end%>
          <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= render 'shared/user_widget' %></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_products.html.erb
<h1>Produkte</h1>

<table class="table">
  <thead>
    <tr>
      <th>Abbildung</th>
      <th>Produkt</th>
      <th>Beschreibung</th>
      <th>Preis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag product.avatar.url(:small) %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency(product.price , :unit=>'€', separator:",", format:"%n%u")%></td>
        <td><%= link_to 'Anzeigen', product, class: 'btn btn-default btn-xs' %>
        <% if user_signed_in? %>
            <% if current_user.admin? %>
                <%= link_to 'Bearbeiten', edit_product_path(product), class: 'btn btn-default btn-xs' %>
                <%= link_to 'Entfernen', product, method: :delete, data: { confirm: 'Sind Sie sicher?' }, class: 'btn btn-default btn-xs'%>
            <% end %>
        <% end %>
          <%= button_to 'Zum Einkaufswagen', line_items_path(:product_id => product), :class => 'btn btn-default btn-xs' %>
        </td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_user_widget.erb
<% if user_signed_in? %>
  <%= link_to 'Abmelden', destroy_user_session_path, :method => :delete %>
  <%= link_to 'Benutzerkonto', accountinformations_show_path %>
  <%= link_to 'Bestellungen', orders_path %>
  <% if current_user.admin %>
  	<%= link_to 'Produkt anlegen', new_product_path %>
  <% end %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
  <%= link_to 'Registrieren', new_user_registration_path %>
<% end %>